AUTHOR_NAME = "davidsantana06"

AUTHOR_URL = "https://davidsantana06.github.io/?h=game"

OMDB_API_URL = "https://www.omdbapi.com/"

OMDB_API_KEY = "YOUR_OMDB_API_KEY"

IMDB_TITLE_URL = "https://www.imdb.com/title/"